### ISSUE TITLE
Multi-line format of `composes` breaks parsing

### ISSUE THREAD

**Issue by viveleroi** [css-modules/postcss-modules-scope#54]
As of prettier v3, they now split CSS declarations by commas so multiple entries in `composes:` declarations are included.

```css
.title {
  composes:
    body-copy,
    text-ellipsis from global;
}
```

```
Internal server error: [postcss] postcss-modules-scope: C:/Users/.../app/components/tree/tree.module.css:132:3: referenced class name "body-copy," in composes not found
[vite]   Plugin: vite:css
[vite]   File: C:/Users/.../app/components/tree/tree.module.css:132:3
[vite]   130|
[vite]   131|  .title {
[vite]   132|    composes:
[vite]      |     ^
[vite]   133|      body-copy,
[vite]   134|      text-ellipsis from global;

```

But this code worked fine as a single line, so we use the `/* prettier ignore */` comment for now.

```css
.title {
  /* prettier-ignore */
  composes: body-copy, text-ellipsis from global;
}
```
